### ISSUE TITLE
~/.gradle/caches/modules-2/files-2.1/de.dfki.mary almost 4 GiB  ?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [marytts/pavoque-data#9]
~/.gradle/caches/modules-2/files-2.1/de.dfki.mary is almost 4 GiB. Is it supposed to be that big?

**Comment by seblemaguer** [comment]
not really I think except if a corpus is downloaded in it, can you indicate the size per subdirectories ?

**Comment by Lew-Rockwell-Fan** [comment]
Thank you. Maybe I messed up the installation. I've done it more than once. I've seen & followed at least 2 different sets of instructions for installation. Should I delete ~/marytts-installer-5.2  and  ~/.gradle and start over?

Is it that I have a lot of voices partly installed? On my local server opened with Firefox, the "Voice:" menu only shows one - "cmu-slt-hsmm en_US female hmm".

 What is a "corpus" in this context?

Output of:
tree -axhFq --du --prune ~/.gradle/caches/modules-2/files-2.1/de.dfki.mary

├── [ 40K]  emotionml-checker-java/
│   └── [ 36K]  1.1/
│       ├── [ 25K]  6f5fa37119440589a80385671aa62a942aa6fb2e/
│       │   └── [ 21K]  emotionml-checker-java-1.1.jar
│       └── [6.5K]  e87fb5f2979ab90f398f006965de0acbc4e9acf/
│           └── [2.5K]  emotionml-checker-java-1.1.pom
├── [ 32K]  marytts/
│   └── [ 28K]  5.2/
│       └── [ 24K]  722431a063e960a71e8fb820570f21fba360194b/
│           └── [ 20K]  marytts-5.2.pom
├── [176K]  marytts-common/
│   └── [172K]  5.2/
│       ├── [162K]  91c78341663e21401cfbf993087a2cb84217e9a0/
│       │   └── [158K]  marytts-common-5.2.jar
│       └── [5.4K]  bafbe1e95e64f5c1aefcebbf63c2e41bc173e015/
│           └── [1.4K]  marytts-common-5.2.pom
├── [5.1M]  marytts-lang-de/
│   └── [5.1M]  5.2/
│       ├── [5.1M]  16ac9daa8efa5a6e79a4f5fe164f55adb74bfcec/
│       │   └── [5.1M]  marytts-lang-de-5.2.jar
│       └── [5.3K]  c200b5dbbc2174fbd8d52f60f7217f1713e97f43/
│           └── [1.3K]  marytts-lang-de-5.2.pom
├── [6.6M]  marytts-lang-en/
│   └── [6.6M]  5.2/
│       ├── [6.6M]  637018181e468a1d3b49c19fa427946d9d21c4a9/
│       │   └── [6.6M]  marytts-lang-en-5.2.jar
│       └── [5.5K]  ea14063ee209cb844cdc1f42a8329e7befa39960/
│           └── [1.5K]  marytts-lang-en-5.2.pom
├── [312K]  marytts-lang-fr/
│   └── [308K]  5.2/
│       ├── [5.4K]  769d71e54235e6966842dcaa9a694ea425a93b57/
│       │   └── [1.4K]  marytts-lang-fr-5.2.pom
│       └── [299K]  7a1aaf79f48c60c6902c723db6c8f314bf1acb38/
│           └── [295K]  marytts-lang-fr-5.2.jar
├── [2.5M]  marytts-lang-it/
│   └── [2.5M]  5.2/
│       ├── [2.5M]  18a27701f5a10643d7988a6c2f191acd25786ffd/
│       │   └── [2.5M]  marytts-lang-it-5.2.jar
│       └── [5.5K]  c20488f80bbda54e7d96827dbdb7248d2f5aeda5/
│           └── [1.5K]  marytts-lang-it-5.2.pom
├── [101K]  marytts-lang-lb/
│   └── [ 97K]  5.2/
│       ├── [ 87K]  52708fd46271e08c97a391cd358c02651ac28344/
│       │   └── [ 83K]  marytts-lang-lb-5.2.jar
│       └── [5.7K]  5523d75d8611ecd73681ab584cd8e2db353dd685/
│           └── [1.7K]  marytts-lang-lb-5.2.pom
├── [ 37K]  marytts-lang-te/
│   └── [ 33K]  5.2/
│       ├── [ 24K]  2c886f655bca76fae42190570485c32387fe6dbd/
│       │   └── [ 20K]  marytts-lang-te-5.2.jar
│       └── [5.1K]  2f99785532a52eb83db98fe69bd50bf886d8147c/
│           └── [1.1K]  marytts-lang-te-5.2.pom
├── [114K]  marytts-lang-tr/
│   └── [110K]  5.2/
│       ├── [101K]  819b8182715c686474fc4a58fc2b44fa8ab1e6b4/
│       │   └── [ 97K]  marytts-lang-tr-5.2.jar
│       └── [5.1K]  e81f8086ec05d3c1e11c8c154feebb9192dd0b2d/
│           └── [1.1K]  marytts-lang-tr-5.2.pom
├── [998K]  marytts-runtime/
│   └── [994K]  5.2/
│       ├── [983K]  c75f16642056cb3342588420dba9eac940f161ef/
│       │   └── [979K]  marytts-runtime-5.2.jar
│       └── [7.2K]  f37a159e6545695904263a346f635428fdcf9a11/
│           └── [3.2K]  marytts-runtime-5.2.pom
├── [1.1M]  marytts-signalproc/
│   └── [1.1M]  5.2/
│       ├── [1.1M]  2da94209eb72bcfa779af2aef43e4f9c9205040/
│       │   └── [1.0M]  marytts-signalproc-5.2.jar
│       └── [5.1K]  33c97334eb5a8ce2c1603075065f35aa578e1310/
│           └── [1.1K]  marytts-signalproc-5.2.pom
├── [251M]  voice-bits1/
│   └── [251M]  5.2/
│       ├── [648K]  258c234dae34d6da9dcf03d0513ae013c4eea35a/
│       │   └── [644K]  voice-bits1-5.2.jar
│       ├── [4.9K]  44a4e6b550a967cc64168648d3eb3915c8e6dec4/
│       │   └── [ 905]  ivy-5.2.xml
│       └── [250M]  69295a129b81a6173b696361b539f8bed03ac30e/
│           └── [250M]  voice-bits1-5.2-data.zip
├── [1.3M]  voice-bits1-hsmm/
│   └── [1.3M]  5.2/
│       ├── [1.3M]  61105d5d6de29fca2473389c1eb2de82b96d36a/
│       │   └── [1.3M]  voice-bits1-hsmm-5.2.jar
│       └── [4.8K]  a38e241c17fdb9f5961cb0a5e609559f1d5d1f5d/
│           └── [ 790]  voice-bits1-hsmm-5.2.pom
├── [254M]  voice-bits2/
│   └── [254M]  5.2/
│       ├── [648K]  5ce8c65c52ec8f3671ad11ec30fe5faf9ab41bd/
│       │   └── [644K]  voice-bits2-5.2.jar
│       ├── [4.9K]  c38acb9c07fb1f5eb7029d70ae843911638e64f2/
│       │   └── [ 905]  ivy-5.2.xml
│       └── [253M]  e7e0df68f7777e7910ac38b652700d800c7d0210/
│           └── [253M]  voice-bits2-5.2-data.zip
├── [257M]  voice-bits3/
│   └── [257M]  5.2/
│       ├── [257M]  6b52d0ac567a3a83b2b41830eab0d3f9171ac639/
│       │   └── [257M]  voice-bits3-5.2-data.zip
│       ├── [652K]  7caf08d0063977d3d92f094c3c01615c5e0e177d/
│       │   └── [648K]  voice-bits3-5.2.jar
│       └── [4.9K]  95c1efb96505ab9e8ce49298aa417c3bfb1fa328/
│           └── [ 905]  ivy-5.2.xml
├── [1.5M]  voice-bits3-hsmm/
│   └── [1.5M]  5.2/
│       ├── [4.8K]  65956a155117941f76a8e9500e36988ce0bce443/
│       │   └── [ 790]  voice-bits3-hsmm-5.2.pom
│       └── [1.5M]  e2c8568d3a0877b75e8439ef10f4537dba72c191/
│           └── [1.5M]  voice-bits3-hsmm-5.2.jar
├── [262M]  voice-bits4/
│   └── [262M]  5.2/
│       ├── [261M]  5395378a883727273a8ad459d216870f842f528a/
│       │   └── [261M]  voice-bits4-5.2-data.zip
│       ├── [648K]  5472e136052257b276392a6151263ec5917204fa/
│       │   └── [644K]  voice-bits4-5.2.jar
│       └── [4.9K]  be1ab980250ad7afb1ee77d70a85372b96d6fe11/
│           └── [ 905]  ivy-5.2.xml
├── [ 91M]  voice-cmu-bdl/
│   └── [ 91M]  5.2/
│       ├── [4.9K]  2465aec77e7b15778c7442298bae1e5e232e6e2d/
│       │   └── [ 911]  ivy-5.2.xml
│       ├── [ 91M]  472594249531cae157aa54519730b03903a5513c/
│       │   └── [ 91M]  voice-cmu-bdl-5.2-data.zip
│       └── [313K]  6476033a61f32c13a8e69ee06b68d5f71d1e13d4/
│           └── [309K]  voice-cmu-bdl-5.2.jar
├── [1012K]  voice-cmu-bdl-hsmm/
│   └── [1008K]  5.2/
│       ├── [4.8K]  5648cbb02db38db450bb01a9f8ab7dd1034f7b91/
│       │   └── [ 792]  voice-cmu-bdl-hsmm-5.2.pom
│       └── [999K]  e9ffb3b98bb71972a7a43c80db8341a828d96e87/
│           └── [995K]  voice-cmu-bdl-hsmm-5.2.jar
├── [3.3M]  voice-cmu-nk-hsmm/
│   └── [3.3M]  5.2/
│       ├── [4.8K]  a59838fbffe3fe988479be10fc7b1755d9d9d230/
│       │   └── [ 791]  voice-cmu-nk-hsmm-5.2.pom
│       └── [3.2M]  de63b6035fab1ee46c42365eb7df1b58b1f7c3d5/
│           └── [3.2M]  voice-cmu-nk-hsmm-5.2.jar
├── [116M]  voice-cmu-rms/
│   └── [116M]  5.2/
│       ├── [4.9K]  7be3e742370aad8c8b133c3d1eea2e85c2b590a0/
│       │   └── [ 911]  ivy-5.2.xml
│       ├── [116M]  b0b9f4545a6a08d777e0a990b62182d1f524e185/
│       │   └── [116M]  voice-cmu-rms-5.2-data.zip
│       └── [325K]  bccf1843655691aae8be95bb3eda7f9018c1e38c/
│           └── [321K]  voice-cmu-rms-5.2.jar
├── [1022K]  voice-cmu-rms-hsmm/
│   └── [1018K]  5.2/
│       ├── [4.8K]  1be30f1adfb6563506c23febef31a077a00d315f/
│       │   └── [ 792]  voice-cmu-rms-hsmm-5.2.pom
│       └── [1009K]  5c838c084706046779948fd1c81369524bb905ca/
│           └── [1005K]  voice-cmu-rms-hsmm-5.2.jar
├── [100M]  voice-cmu-slt/
│   └── [100M]  5.2/
│       ├── [316K]  24afca48d74dedafa0380e66f175657486e7fa61/
│       │   └── [312K]  voice-cmu-slt-5.2.jar
│       ├── [ 99M]  4ece4c4b8f3d6eeaaf2ac2082ab569dccc963a15/
│       │   └── [ 99M]  voice-cmu-slt-5.2-data.zip
│       └── [4.9K]  95fddcdd5365bdb3b08266db03162812a26869d8/
│           └── [ 911]  ivy-5.2.xml
├── [1.2M]  voice-cmu-slt-hsmm/
│   └── [1.2M]  5.2/
│       ├── [7.1K]  30fef5350815b0f84a59b1ddf9411a97d878de3f/
│       │   └── [3.1K]  voice-cmu-slt-hsmm-5.2.pom
│       └── [1.2M]  cae0223460ab045dc2187b855b50754c483220b0/
│           └── [1.2M]  voice-cmu-slt-hsmm-5.2.jar
├── [158M]  voice-dfki-obadiah/
│   └── [158M]  5.2/
│       ├── [4.9K]  905d7682cdb167c078207102fba53d5e400843a1/
│       │   └── [ 926]  ivy-5.2.xml
│       ├── [366K]  997a774bd794b11dbed4d10a10ced7be911a9bf1/
│       │   └── [362K]  voice-dfki-obadiah-5.2.jar
│       └── [157M]  ff865be5859b1aa4637b345dd44f57b50e246a72/
│           └── [157M]  voice-dfki-obadiah-5.2-data.zip
├── [1.2M]  voice-dfki-obadiah-hsmm/
│   └── [1.2M]  5.2/
│       ├── [1.2M]  1453726474864a4513115f886958cc8d4c46fd06/
│       │   └── [1.2M]  voice-dfki-obadiah-hsmm-5.2.jar
│       └── [4.8K]  2a7c70f0fa43e5ad618698406de3b6d69ff2779/
│           └── [ 797]  voice-dfki-obadiah-hsmm-5.2.pom
├── [154M]  voice-dfki-ot/
│   └── [154M]  5.2/
│       ├── [478K]  737eae337f5af0bbedb13a2966568bfdfa9ab47/
│       │   └── [474K]  voice-dfki-ot-5.2.jar
│       ├── [4.9K]  b6029c8321a849565c5a32012ce1f78376fb2a97/
│       │   └── [ 911]  ivy-5.2.xml
│       └── [153M]  d25b5da1ce03843cb4d74cd3eaa68bfe0a12f6bd/
│           └── [153M]  voice-dfki-ot-5.2-data.zip
├── [1.3M]  voice-dfki-ot-hsmm/
│   └── [1.3M]  5.2/
│       ├── [1.3M]  5e40b5f2be75f3ccb1666b0e3046aaabcbc3484d/
│       │   └── [1.3M]  voice-dfki-ot-hsmm-5.2.jar
│       └── [4.8K]  c5b3fce43c9ff4ed66065833d7e28ceb33300919/
│           └── [ 792]  voice-dfki-ot-hsmm-5.2.pom
├── [428M]  voice-dfki-pavoque-neutral/
│   └── [428M]  5.2/
│       ├── [4.9K]  16cf33292f7c6d05e7653b1b7748b67cb4ee3c95/
│       │   └── [ 950]  ivy-5.2.xml
│       ├── [427M]  866971c933370e412e5bba8f7dd2d04c1b181690/
│       │   └── [427M]  voice-dfki-pavoque-neutral-5.2-data.zip
│       └── [1.2M]  c84410f52a78bd814a739defc4fcd8aaddacd476/
│           └── [1.2M]  voice-dfki-pavoque-neutral-5.2.jar
├── [2.7M]  voice-dfki-pavoque-neutral-hsmm/
│   └── [2.7M]  5.2/
│       ├── [4.8K]  2e94df4c179361c71f9f12875cb590eecf13c434/
│       │   └── [ 805]  voice-dfki-pavoque-neutral-hsmm-5.2.pom
│       └── [2.7M]  f0a9b2c930d6b5c14a1d8c00267f93981622abe8/
│           └── [2.7M]  voice-dfki-pavoque-neutral-hsmm-5.2.jar
├── [668M]  voice-dfki-pavoque-styles/
│   └── [668M]  5.2/
│       ├── [1.8M]  37dd776e0054a31d7b49dd08718ce7fd4773353a/
│       │   └── [1.8M]  voice-dfki-pavoque-styles-5.2.jar
│       ├── [4.9K]  42f12f0fdfb65963763c7ad49accbb780d28e645/
│       │   └── [ 947]  ivy-5.2.xml
│       └── [667M]  7b2ed017b4c911835119594bc69360feee40faa8/
│           └── [667M]  voice-dfki-pavoque-styles-5.2-data.zip
├── [107M]  voice-dfki-poppy/
│   └── [107M]  5.2/
│       ├── [107M]  1a587eba1aeb491d70e733edafd6c4c1b53b9afb/
│       │   └── [107M]  voice-dfki-poppy-5.2-data.zip
│       ├── [288K]  cddc9a22704fead464cc62dd09ef663fdbbbe87/
│       │   └── [284K]  voice-dfki-poppy-5.2.jar
│       └── [4.9K]  ed30f19abfc173aa333155fc8436fc6cb259ff10/
│           └── [ 920]  ivy-5.2.xml
├── [1010K]  voice-dfki-poppy-hsmm/
│   └── [1006K]  5.2/
│       ├── [997K]  5fd22f335592e3162411e935dcaf511455abcd2a/
│       │   └── [993K]  voice-dfki-poppy-hsmm-5.2.jar
│       └── [4.8K]  c3e613702eb68a239fa005a0fc8b4f0e68e726e2/
│           └── [ 795]  voice-dfki-poppy-hsmm-5.2.pom
├── [280M]  voice-dfki-prudence/
│   └── [280M]  5.2/
│       ├── [668K]  8f00792fbf2634991f8585c6c3180cc04e0ea379/
│       │   └── [664K]  voice-dfki-prudence-5.2.jar
│       ├── [280M]  db5f59b47c42a3b36b0aaeda6b951946f9c5b317/
│       │   └── [279M]  voice-dfki-prudence-5.2-data.zip
│       └── [4.9K]  db8739175edfe5238113d9bb412a15452f4087a/
│           └── [ 929]  ivy-5.2.xml
├── [1.5M]  voice-dfki-prudence-hsmm/
│   └── [1.5M]  5.2/
│       ├── [4.8K]  b7947fcb2cd68d0f602b350a5d04935b260d4236/
│       │   └── [ 798]  voice-dfki-prudence-hsmm-5.2.pom
│       └── [1.5M]  b8d39bba3655cf7788b7089e6d44a49f2b610cdd/
│           └── [1.5M]  voice-dfki-prudence-hsmm-5.2.jar
├── [156M]  voice-dfki-spike/
│   └── [156M]  5.2/
│       ├── [4.9K]  3381f6f9616ce83871d78ba95982bde9396fc43b/
│       │   └── [ 920]  ivy-5.2.xml
│       ├── [156M]  3413eac7704a1ba15c978f66604fa82dc43ae465/
│       │   └── [156M]  voice-dfki-spike-5.2-data.zip
│       └── [406K]  7d79ef51a8344bda99964074ed246025e215139a/
│           └── [402K]  voice-dfki-spike-5.2.jar
├── [1.1M]  voice-dfki-spike-hsmm/
│   └── [1.0M]  5.2/
│       ├── [1.0M]  90974fb054e2835b8029b1fb5984624d8fc124f8/
│       │   └── [1.0M]  voice-dfki-spike-hsmm-5.2.jar
│       └── [4.8K]  a73bec5044440a55ad8a22cdab8d5d0d9482d2a9/
│           └── [ 795]  voice-dfki-spike-hsmm-5.2.pom
├── [204M]  voice-enst-camille/
│   └── [204M]  5.2/
│       ├── [447K]  657744742126b4d3a65a1a0e981da0634787f8fc/
│       │   └── [443K]  voice-enst-camille-5.2.jar
│       ├── [204M]  833ffa49fe783d560073eb654f7d1bafb40c510b/
│       │   └── [204M]  voice-enst-camille-5.2-data.zip
│       └── [4.9K]  a0c62c31e1d5997a4df4e113a57ee451a591d530/
│           └── [ 926]  ivy-5.2.xml
├── [1.5M]  voice-enst-camille-hsmm/
│   └── [1.5M]  5.2/
│       ├── [1.5M]  2b47b9145b8deb54c897b64ecd59e309f1e443f4/
│       │   └── [1.4M]  voice-enst-camille-hsmm-5.2.jar
│       └── [4.8K]  c93562706960150874bcc695c1a0e722127c6029/
│           └── [ 797]  voice-enst-camille-hsmm-5.2.pom
├── [1.6M]  voice-enst-dennys-hsmm/
│   └── [1.6M]  5.2/
│       ├── [4.8K]  e61838ec459446219d867134793e11b8a278e13a/
│       │   └── [ 796]  voice-enst-dennys-hsmm-5.2.pom
│       └── [1.6M]  ea5f31dcb5b55988edc56c063274e48b32a0a5d7/
│           └── [1.6M]  voice-enst-dennys-hsmm-5.2.jar
├── [1.4M]  voice-istc-lucia-hsmm/
│   └── [1.4M]  5.2/
│       ├── [4.8K]  44f55a6609e8f20b2a4e3123be86afac22321b3e/
│       │   └── [ 795]  voice-istc-lucia-hsmm-5.2.pom
│       └── [1.4M]  bfe7459c4777eda09e98a811a7895e69a2c55e02/
│           └── [1.4M]  voice-istc-lucia-hsmm-5.2.jar
├── [113M]  voice-marylux-lb/
│   └── [113M]  5.2/
│       ├── [418K]  1efb7cfea0b7cd422a1672fe53755f622fcbd38b/
│       │   └── [414K]  voice-marylux-lb-5.2.jar
│       ├── [113M]  946d559db837f70252963ace71b8e0b85e20e4c8/
│       │   └── [113M]  voice-marylux-lb-5.2-data.zip
│       └── [4.9K]  9badbf8e439da2d9baae27bd5b69f1f5762a53ac/
│           └── [ 920]  ivy-5.2.xml
└── [144M]  voice-upmc-jessica/
    └── [144M]  5.2/
        ├── [4.9K]  22e24d9b81f934d7dccd788d4fce57805186299f/
        │   └── [ 926]  ivy-5.2.xml
        ├── [144M]  2ee027d07b7cd946df3ed9ea7cd83715ff53375c/
        │   └── [144M]  voice-upmc-jessica-5.2-data.zip
        └── [325K]  fc329e6c7162e536c1b3bd02ba5b657421697f7e/
            └── [321K]  voice-upmc-jessica-5.2.jar

 3.7G used in 192 directories, 104 files

**Comment by seblemaguer** [comment]
What is taking space are the voices (so no corpus). If you run the marytts-installer technically you should see all the voices. However, this is not an issue for this repository so I close it

**Comment by Lew-Rockwell-Fan** [comment]
Then shouldn't the "Voice:" menu on the local server show more than 1 voice then?
Anyway, I just deleted the .gradle directory & started the server with "marytts server". It created a new .gradle that is less than 100 MiB marytts  works  the same way it did. I think I kept trying to install voices with the gui and none of them ever showed up on the menu.

**Comment by psibre** [comment]
For the record, all of the above might have been explained by the [Download cache](https://github.com/marytts/marytts-installer#download-cache) section of the marytts-installer readme.
